[package]
name = "tg-voting-contract"
version = "0.8.1"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2018"
description = "Generic utils for building voting contracts for tgrade"
repository = "https://github.com/confio/poe-contracts"
homepage = "https://tgrade.finance"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-utils = "0.13.2"
tg3 = { path = "../../packages/tg3", version = "0.8.1" }
cw-storage-plus = "0.13.2"
cosmwasm-std = "1.0.0-beta8"
schemars = "0.8.1"
serde = { version = "1", default-features = false, features = ["derive"] }
tg4 = { path = "../tg4", version = "0.8.1" }
tg-bindings = { path = "../bindings", version = "0.8.1" }
tg-utils = { version = "0.8.1", path = "../utils" }
thiserror = { version = "1" }

[dev-dependencies]
anyhow = "1"
cosmwasm-schema = "1.0.0-beta8"
cw-multi-test = "0.13.2"
derivative = "2"
tg-bindings-test = { path = "../../packages/bindings-test", version = "0.8.1" }
tg4-engagement = { path = "../../contracts/tg4-engagement", version = "0.8.1", features = ["library"] }
