[package]
name = "tg3"
version = "0.17.1"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2018"
description = "Tgrade-3 Interface: On-Chain MultiSig/Voting contracts"
repository = "https://github.com/confio/poe-contracts"
homepage = "https://tgrade.finance"
license = "Apache-2.0"

[dependencies]
cosmwasm-std = "1.1.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
tg-bindings = { version = "0.17.1", path = "../../packages/bindings" }
tg-utils = { version = "0.17.1", path = "../../packages/utils" }

[dev-dependencies]
cosmwasm-schema = "1.1.9"
