[package]
name = "tg4"
version = "0.17.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Tgrade-4 Interface: Groups Members"
repository = "https://github.com/confio/poe-contracts"
homepage = "https://tgrade.finance"
license = "Apache-2.0"

[dependencies]
cosmwasm-std = "1.1.9"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
tg-bindings = { path = "../bindings", version = "0.17.1" }

[dev-dependencies]
cosmwasm-schema = "1.1.9"
